name: GitHub Pages

on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed
    branches:
      - master

jobs:
  configure-pages:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v4
      with:
        static_site_generator: angular
